"""Create coachee_profiles table

Revision ID: 1eaa416c2b69
Revises: 19af78344b02
Create Date: 2025-09-17 16:07:33.957948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1eaa416c2b69'
down_revision: Union[str, Sequence[str], None] = '19af78344b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('coach_profiles')
#     op.drop_index(op.f('email'), table_name='users')
#     op.drop_table('users')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('users',
#     sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
#     sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
#     sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
#     sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
#     sa.Column('role', mysql.ENUM('coach', 'coachee'), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_0900_ai_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_index(op.f('email'), 'users', ['email'], unique=True)
#     op.create_table('coach_profiles',
#     sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('bio', mysql.TEXT(), nullable=True),
#     sa.Column('expertise', mysql.VARCHAR(length=255), nullable=True),
#     sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
#     sa.Column('availability', mysql.ENUM('available', 'unavailable'), nullable=True),
#     sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('coach_profiles_ibfk_1')),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_0900_ai_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     # ### end Alembic commands ###

def upgrade() -> None:
    op.create_table(
        'coachee_profiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.Column('expertise', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('availability', sa.Enum('available', 'unavailable', name='availabilityenum'), nullable=True),
        sa.Column('image_url', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),  # ForeignKey constraint
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

def downgrade() -> None:
    op.drop_table('coachee_profiles')

