"""Fix ForeignKey import and relationship

Revision ID: 59f81b3df408
Revises: 0447b7ef7136
Create Date: 2025-09-17 15:16:44.979227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59f81b3df408'
down_revision: Union[str, Sequence[str], None] = '0447b7ef7136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users')  # Remove this line to prevent dropping the users table
    # You can add any schema changes here, like adding columns or altering the table if needed.
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # If you have dropped columns or tables, you can re-create them here. For example:
    op.create_table(
        'users',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('role', mysql.ENUM('coach', 'coachee'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
