"""Fix session model

Revision ID: c4ed84b3b614
Revises: 1eaa416c2b69
Create Date: 2025-09-17 17:33:25.953322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4ed84b3b614'
down_revision: Union[str, Sequence[str], None] = '1eaa416c2b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###

    # Create the sessions table if it doesn't exist
    op.create_table(
        'sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('coach_id', sa.Integer(), nullable=False),  # Add coach_id
        sa.Column('coachee_id', sa.Integer(), nullable=False),  # Add coachee_id
        sa.Column('topic', sa.String(255), nullable=False),  # Add topic
        sa.Column('location', sa.String(255), nullable=False),  # Add location
        sa.Column('capacity', sa.Integer(), nullable=False),  # Add capacity
        sa.Column('time', sa.DateTime(), nullable=False),  # Add time
        sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'completed', name='sessionstatus'), nullable=False),  # Add status
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['coach_id'], ['users.id']),
        sa.ForeignKeyConstraint(['coachee_id'], ['users.id']),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    # Create foreign key constraints for coach_id and coachee_id columns
    op.create_foreign_key('sessions_coach_id_fk', 'sessions', 'users', ['coach_id'], ['id'])
    op.create_foreign_key('sessions_coachee_id_fk', 'sessions', 'users', ['coachee_id'], ['id'])

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###

    # Drop the columns if you want to rollback the changes
    op.drop_constraint('sessions_coach_id_fk', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_coachee_id_fk', 'sessions', type_='foreignkey')

    op.drop_column('sessions', 'coach_id')
    op.drop_column('sessions', 'coachee_id')
    op.drop_column('sessions', 'topic')
    op.drop_column('sessions', 'location')
    op.drop_column('sessions', 'capacity')
    op.drop_column('sessions', 'time')
    op.drop_column('sessions', 'status')

    # ### end Alembic commands ###
